spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello_random_fact # nombre de la variable:spring DataSource url
    username: ironhacker # variable:  spring data source username
    password: 1r0nh4ck3r
    driver-class-name: com.mysql.cj.jdbc.Driver # drivers que usaremos para conectar a la base de datos
  jpa: # nos permite hacer operaciones con nuestra data base
    show-sql: true # show the commands that are being executed
    generate-ddl : true
    hibernate:
      ddl-auto: update